services:
  db:
    image: postgres:13-alpine
    container_name: library_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    environment:
      POSTGRES_USER: user     
      POSTGRES_PASSWORD: password
      POSTGRES_DB: librarydb     
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d librarydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: . 
    container_name: library_flask_app
    ports:
      - "5000:5000" 
    depends_on:
      db:
        condition: service_healthy 
    environment:
      FLASK_APP: run.py 
      FLASK_ENV: development 
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/librarydb
    volumes:
      - .:/app
    command: >
      sh -c "python -c 'from run import create_tables_and_seed_data; create_tables_and_seed_data()' &&
             gunicorn -w 4 -b 0.0.0.0:5000 run:app"

volumes:
  postgres_data: 